---
# Inventory file is in /etc/ansible/hosts
# run command ansible-playbook {filename} -u {username} -K
- name: Configure VaultWarden 
  hosts: localhost
  vars_files:
    - /users/kevin/.ansible_secrets.yml
  vars:
    deployment_name: vaultwarden
    image_name: vaultwarden/server
    image_tag: 1.34.3-alpine
    namespace_name: nginx
    env_map:
      - name: DOMAIN 
        value: "https://vw.supergoon.com"
    ports:
      - container_port: 80
        name: http
    service_name: vaultwarden-service
    service_selector: vaultwarden
    service_type: ClusterIP
    service_ports:
      - name: http
        port: 80
        target_port: 80
    volumes:
      - path: /mnt/vault
        name: vault
    volume_mounts:
      - path: /data
        name: vault
      

  tasks:
    - name: Render Deployment manifest
      template:
        src: ../../../templates/k8s/deployment.yaml.j2
        dest: /tmp/{{ deployment_name }}-deployment.yaml
        lstrip_blocks: true
        trim_blocks: true

    - name: Render Service manifest
      template:
        src: ../../../templates/k8s/service.yaml.j2
        dest: /tmp/{{ service_name }}.yaml
        lstrip_blocks: true
        trim_blocks: true

    - name: Apply Kubernetes manifests
      k8s:
        state: present
        src: "{{ item }}"
      loop:
        - /tmp/{{ service_name }}.yaml
        - /tmp/{{ deployment_name }}-deployment.yaml
